trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DownloadBuildArtifacts@0
  inputs:
    buildType: 'current'
    downloadType: 'single'
    artifactName: 'drop'
    downloadPath: '$(System.DefaultWorkingDirectory)'

- script: ls $(System.DefaultWorkingDirectory)
  displayName: 'List files in default working directory'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Visual Studio Enterprise Subscription (3bc037e8-16d9-41ed-8f5f-149eb5e80111)'
    appType: 'webApp'
    appName: 'lab841226'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
    deploymentMethod: 'auto'

